### ISSUE TITLE
No module named arm

### ISSUE THREAD

**Issue by windhl** [axt/bingraphvis#5]
hi, axt,
I just setup your great work, but in the installation path: /usr/.../python2.7/dist-packages/bingraphvis not found arm, and when I ran your sample, it gave me belows, and I hope your answer :) :

Traceback (most recent call last):
  File "cfg.py", line 2, in <module>
    from angrutils import *
  File "/usr/local/lib/python2.7/dist-packages/angrutils/__init__.py", line 1, in <module>
    from .visualize import *
  File "/usr/local/lib/python2.7/dist-packages/angrutils/visualize.py", line 6, in <module>
    from bingraphvis.angr import *
  File "/usr/local/lib/python2.7/dist-packages/bingraphvis/angr/__init__.py", line 7, in <module>
    from .factory import *
  File "/usr/local/lib/python2.7/dist-packages/bingraphvis/angr/factory.py", line 4, in <module>
    from .arm import *
ImportError: No module named arm

**Comment by windhl** [comment]
maybe fix setup.py as:
 packages=['bingraphvis', 'bingraphvis.angr', 'bingraphvis.angr.x86', **'bingraphvis.angr.arm'**],

**Comment by axt** [comment]
Pushed a fix, thanks!
